// Minimal sample. Add more operators as needed.
const OPERATORS = [
  {
    name: "Sledge",
    side: "Attacker",
    speed: 2,
    armor: 2,
    ctu: "SAS",
    country: "UK",
    gadgetTags: ["breach", "soft-breach", "hammer"],
  },
  {
    name: "Thatcher",
    side: "Attacker",
    speed: 2,
    armor: 2,
    ctu: "SAS",
    country: "UK",
    gadgetTags: ["emp", "utility-denial", "electronics"],
  },
  {
    name: "Ash",
    side: "Attacker",
    speed: 3,
    armor: 1,
    ctu: "FBI SWAT",
    country: "USA",
    gadgetTags: ["breach", "ranged-breach", "soft-breach"],
  },
  {
    name: "Thermite",
    side: "Attacker",
    speed: 2,
    armor: 2,
    ctu: "FBI SWAT",
    country: "USA",
    gadgetTags: ["hard-breach", "breach"],
  },
  {
    name: "Montagne",
    side: "Attacker",
    speed: 1,
    armor: 3,
    ctu: "GIGN",
    country: "France",
    gadgetTags: ["shield", "frontline"],
  },
  {
    name: "Twitch",
    side: "Attacker",
    speed: 2,
    armor: 2,
    ctu: "GIGN",
    country: "France",
    gadgetTags: ["drone", "electronics", "utility-denial"],
  },
  {
    name: "Rook",
    side: "Defender",
    speed: 1,
    armor: 3,
    ctu: "GIGN",
    country: "France",
    gadgetTags: ["armor", "support"],
  },
  {
    name: "Doc",
    side: "Defender",
    speed: 1,
    armor: 3,
    ctu: "GIGN",
    country: "France",
    gadgetTags: ["heal", "support", "stim"],
  },
  {
    name: "Jäger",
    side: "Defender",
    speed: 2,
    armor: 2,
    ctu: "GSG 9",
    country: "Germany",
    gadgetTags: ["projectile-denial", "ads", "utility-denial"],
  },
  {
    name: "Bandit",
    side: "Defender",
    speed: 3,
    armor: 1,
    ctu: "GSG 9",
    country: "Germany",
    gadgetTags: ["electric", "wall-denial", "barbed-wire"],
  },
  {
    name: "Smoke",
    side: "Defender",
    speed: 2,
    armor: 2,
    ctu: "SAS",
    country: "UK",
    gadgetTags: ["smoke", "area-denial", "toxic"],
  },
  {
    name: "Mute",
    side: "Defender",
    speed: 2,
    armor: 2,
    ctu: "SAS",
    country: "UK",
    gadgetTags: ["jammer", "electronics", "intel-denial"],
  },
  {
    name: "Valkyrie",
    side: "Defender",
    speed: 2,
    armor: 2,
    ctu: "Navy SEALs",
    country: "USA",
    gadgetTags: ["camera", "intel"],
  },
  {
    name: "Caveira",
    side: "Defender",
    speed: 3,
    armor: 1,
    ctu: "BOPE",
    country: "Brazil",
    gadgetTags: ["roam", "interrogation", "stealth"],
  },
  {
    name: "Mira",
    side: "Defender",
    speed: 1,
    armor: 3,
    ctu: "GEO",
    country: "Spain",
    gadgetTags: ["vision", "one-way", "window"],
  },
  {
    name: "Jackal",
    side: "Attacker",
    speed: 2,
    armor: 2,
    ctu: "GEO",
    country: "Spain",
    gadgetTags: ["tracker", "roam-hunter", "footsteps"],
  },
];
